server:
  port: 8080
spring:
  rabbitmq:
    addresses: 192.168.64.130:5672
    username: guest
    password: guest
    publisher-confirm-type: correlated
logging:
  level:
    org.springframework: INFO
